'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheHeader } from './components/Header'
import { TheFooter } from './components/Footer'
import { useState } from 'react'
import { ActiveContext, ActiveContextProvider } from '@/app/context'
import { IOperator } from '@/models'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ActiveContextProvider>
          <TheHeader />
          <main className="container"> {children}</main>
          <TheFooter />
        </ActiveContextProvider>
      </body>
    </html>
  )
}
