import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TheHeader } from './components/Header'
import { TheFooter } from './components/Footer'
import { useState } from 'react'
import { ActiveContext } from '@/Context/context'
import { IOperator } from '@/models'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isActive, setIsActive] = useState(false)
  const [operatore, setOperator] = useState<IOperator>({
    id: 0,
    title: '',
    image: '',
  })
  const initialValues = {
    isActive,
    setIsActive,
    operatore,
    setOperator,
  }
  return (
    <html lang="en">
      <body>
        <ActiveContext.Provider value={initialValues}>
          <TheHeader />
          <main className="container"> {children}</main>
          <TheFooter />
        </ActiveContext.Provider>
      </body>
    </html>
  )
}
